### ISSUE TITLE
enderdragon

### ISSUE THREAD

**Issue by nososho** [LAX1DUDE/eaglercraft#103]
The ender dragon is invisible and the bossbar wont show

**Comment by LAX1DUDE** [comment]
Can you try and join the underlying Bukkit server using normal vanilla Minecraft 1.5.2 instead of Eaglercraft and determine if the ender dragon is also missing in regular vanilla Minecraft 1.5.2. Launch it and try joining 'localhost:25569' using vanilla Minecraft 1.5.2 and travel to the end again and check if the ender dragon is still missing with the official game.

**Comment by nososho** [comment]
Minecraft 1.5.2 keeps crashing when I launch it in the official mc launcher so I can't try it out, sorry

**Comment by LAX1DUDE** [comment]
> Minecraft 1.5.2 keeps crashing when I launch it in the official mc launcher so I can't try it out, sorry

I had the same problem when I first tried to steal the 1.5.2 version of game out of the minecraft launcher directory. Try changing the game's directory in the launcher to somewhere other than the default, if you don't know how please google.

**Comment by LAX1DUDE** [comment]
> Okay so I did what you told me to, and minecraft launched! Okay, back to my original problem, I seem to be able to see the ender dragon and the bossbar on vanilla 1.5.2

Oh for fucks sake, okay I'll look into this but I literally have no idea how this could've happened and I am not looking forward to trying to figure out. I will solve this problem at all costs though, I can not sleep unless I know my browser version port is a 1:1 replica of real minecraft that works on all regular minecraft servers.

Can you hear the ender dragon sound effects? It could be a rendering glitch because the boss bar gets 'enabled' every time the game draws the ender dragon 3D model, that's how those boss bar mob spawners make the boss bars it's because the game is drawing the ender dragon. If the game glitches while drawing the ender dragon it would make the ender dragon invisible and also will fail to enable the boss bar.

The ender dragon will still make sound effects though regardless if it is present on the screen or not, so if you can still hear it and just not see it then that would mean only the code that draws the ender dragon is broken. Otherwise, this is a much more complicated and serious problem with the code.

**Comment by nososho** [comment]
Okay so it seems like the ender dragon sounds do not play, so I'm guessing its not that critical right?

**Comment by nososho** [comment]
Oh shoot, sorry I had my tab muted. The ender dragon sounds do play.

**Comment by LAX1DUDE** [comment]
> Oh shoot, sorry I had my tab muted. The ender dragon sounds do play.

Okay thanks that makes this much easier of a problem to solve, thanks for letting me know

**Comment by nososho** [comment]
No worries! Could you please remind me when this issue is fixed? Thanks!

**Comment by MegaTheLEGEND** [comment]
when this is fixed/ updated, how would i update my replit server? do i have to re-fork it and start ever?

**Comment by LAX1DUDE** [comment]
> when this is fixed/ updated, how would i update my replit server? do i have to re-fork it and start ever? or is it I just need to use the latest web files from the stable download folder?

latest web 'classes.js'

**Comment by LAX1DUDE** [comment]
Fixed.

[https://github.com/LAX1DUDE/eaglercraft/commit/081dd6ce3f94a6a2678d2626e0c98470a3414ac7](https://github.com/LAX1DUDE/eaglercraft/commit/081dd6ce3f94a6a2678d2626e0c98470a3414ac7)

**Comment by nososho** [comment]
Hey! Any updates?

**Comment by LAX1DUDE** [comment]
> Hey! Any updates?

I said it's fixed [https://github.com/LAX1DUDE/eaglercraft/commit/081dd6ce3f94a6a2678d2626e0c98470a3414ac7](https://github.com/LAX1DUDE/eaglercraft/commit/081dd6ce3f94a6a2678d2626e0c98470a3414ac7)

**Comment by nososho** [comment]
> > Hey! Any updates?
> 
> I said it's fixed [081dd6c](https://github.com/LAX1DUDE/eaglercraft/commit/081dd6ce3f94a6a2678d2626e0c98470a3414ac7)

Oh sorry, I didn't refresh my page so your message did not appear, anyways, thanks!

**Comment by nososho** [comment]
> Fixed.
> 
> [081dd6c](https://github.com/LAX1DUDE/eaglercraft/commit/081dd6ce3f94a6a2678d2626e0c98470a3414ac7)

Hmm, it seems that the ender dragon and it's bossbar still don't appear...

**Comment by nososho** [comment]
Sorry, nevermind, I had to clear my cookies
